[package]
name = "imu-rs"
version = "0.1.0"
edition = "2021"

# [target.thumbv6m-none-eabi]
# runner = "probe-run --chip RP2040"
# Default is to copy the generated file on the USB mass storage. Loot at
# .cargo/config.

[dependencies]
cortex-m = "0.7.7"
cortex-m-rt = "0.7.3"
embedded-hal = { version = "0.2.7", features = ["unproven"] }
format_no_std = "1.0.0"
fugit = "0.3.7"
heapless = "0.7.16"
nb = "1.0.0"
shared-bus = "0.2.4"

panic-halt = "0.2.0"

# If you're not going to use a Board Support Package you'll need these:
rp2040-hal = { version="0.9.0", features=["rt", "critical-section-impl"] }
rp2040-boot2 = "0.3.0"

usb-device = "0.2.9"
usbd-serial = "0.1.1"
usbd-hid = "0.6.1"

smart-leds = "0.3.0"
ws2812-pio = "0.7.0"

mpu6050 = "0.1.6"
qmc5883l = "0.0.1"
